### ISSUE TITLE
Want to use Laravel?

### ISSUE THREAD

**Issue by lazytyper** [MajorPlayz/ComluComliCom#1]
I could set up your project so you can use Laravel for it, but I don't have time right now.
Maybe later.

**Comment by MajorPlayz** [comment]
I had a look at it but actually is laravel?

**Comment by lazytyper** [comment]
I'm not sure, I'm using that. Maybe something is better, idk.
You can search here: https://www.google.com/trends/explore?q=laravel
I did not use Google Trends yet.

**Comment by lazytyper** [comment]
My nephew suggest me to work with node.js (node express, sails.js) . There are so many  platforms... but node.js is better than PHP, you can use the code for `electron` apps or  `meteor`.

You have to select the best language / framework today and the mixins.
